version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANPROJ20MayProject
  gitServerName: MJAN_GitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  gitServerName: MJAN_GitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQAJDBCAdapterTests
  gitServerName: MJAN_GitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
