version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANPROJ20MayProject
  gitServerName: MJAN_GitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: MJAN_GitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: MJAN_GitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: WmSalesforceRESTProvider
  version: 10.7.0.0.187
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: MJAN_GitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.mjanproj20may.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.connections:MJANSalesforceOauth
  packages:
  - name: MJANPROJ20MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.mjanproj20may.integrations:CSTestConnector
  packages:
  - name: MJANPROJ20MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.mjanproj20may.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.operations.actions:CreateAccount
  packages:
  - name: MJANPROJ20MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: project.mjanproj20may.integrations:CStest
  packages:
  - name: MJANPROJ20MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: SIQACloudStreamsTests:connetorOperations
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: SIQACloudStreamsTests:createAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: SIQACloudStreamsTests:retrieveAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: SIQACloudStreamsTests:deleteAccountConnectorService
  packages:
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: project.mjanproj20may.integrations:DBTest
  packages:
  - name: MJANPROJ20MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: SIQAJDBCAdapterTests.adapterServices:getData
  packages:
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.mjanproj20may.integrations:getGV
  packages:
  - name: MJANPROJ20MayProject
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: SIQACloudStreamsTests
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: GB_1:readGlobalvariable
  packages:
  - name: DADA_GlobalVariable1
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
configurationVariables:
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.providerUrl
  : https://sag53-dev-ed.develop.my.salesforce.com
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth.accessToken
  : "{AES}h1r1CmTvU65r25EqPgWKVf2td05qEbSBpNIV1JNq+vb22NXaCPZswXJyJ4c4RtO8BbKtFOddMA541DgeWX67vvl4ZyqNbUjqGqTnE+9naGXdn/7vZhhel2eCRIMBrmncUJ+zTqqzd/Um4AHWyjT8QWmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.authorizationHeaderInTokenRefresh
  : "false"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.accessTokenRefreshURLRequest
  : URL Query String
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.refreshToken
  : "{AES}z0OyKRGMCuSrw5+VwAKX9/oM6BIKjPeYnDaBN96E5WE51ihADTbuVPxNgEzibj4QZ+EkdVmuzavsuGo7cSFFyYqssvQYfu051UABuvfGck7t1OSEZFCXaC8TXIG3+XjN"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.authenticationServerUrl
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.scope
  : offline_access api refresh_token
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth.consumerSecret
  : "{AES}ePv9vDKXdd6A2HDsPDBAO8y1Fe9R7m6Dya5xSCLlAK353vKmgg/uiZT0YAoUU42Eojf9A5EvRE+pSL3aLrpBNWmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.authorizationServerUrl
  : https://login.salesforce.com/services/oauth2/authorize
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.readTimeout
  : "30000"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.refreshAccessToken
  : "true"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.authorizationHeaderPrefix
  : OAuth
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth.consumerId
  : 3MVG9k02hQhyUgQCKlnwOVc1lTfY9AqPHmUIRA6I.ZqYzln.F3Vuok.Rk6d6F00IhbOJxstGzhIJDyuJGd0ft
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cx.grant_type
  : refresh_token
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.connectTimeout
  : "30000"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.sockBuffSize
  : "8192"
  ? iscloudstreamsconnectorservice.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..operations..actions:CreateAccount.connectionAlias
  : project.mjanproj20may.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.connections:MJANSalesforceOauth
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.startupRetryCount
  : "0"
  ? iscloudstreamsconnectorservice.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..operations..actions:CreateAccount.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.poolable
  : "true"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.retryCount
  : "4"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.oauth_v20.accessTokenRefreshURL
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..mjanproj20may..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MJANSalesforceOauth.timeoutType
  : auto
